export enum ListingType {
  GARAGE = 'GARAGE',
  STORAGE = 'STORAGE',
  PARKING = 'PARKING',
  MOTO_SLOT = 'MOTO_SLOT',
  WORKSHOP = 'WORKSHOP',
  MINI_FACTORY = 'MINI_FACTORY',
  BOAT_SLOT = 'BOAT_SLOT',
  OTHER = 'OTHER',
}
