export enum SpaceAmenity {
  SECURITY = 'SECURITY',
  VIDEO_SURVEILLANCE = 'VIDEO_SURVEILLANCE',
  HEATING = 'HEATING',
  VENTILATION = 'VENTILATION',
  WATER_SUPPLY = 'WATER_SUPPLY',
  ELECTRICITY = 'ELECTRICITY',
  WIFI = 'WIFI',
  ETHERNET = 'ETHERNET',
}
