export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  BOOKING_PAYMENT = 'BOOKING_PAYMENT',
  BOOKING_PAYOUT = 'BOOKING_PAYOUT',
  REFUND = 'REFUND',
  COMMISSION = 'COMMISSION',
}
